version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: complykort-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: complykort
      POSTGRES_USER: complykort
      POSTGRES_PASSWORD: complykort_secure_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - complykort-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complykort -d complykort"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: complykort-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - complykort-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  complykort-network:
    driver: bridge
